### ISSUE TITLE
User agent shouldn't be Googlebot

### ISSUE THREAD

**Issue by vladc** [ourren/ip-api#1]
The user agent is Mozilla/5.0 (compatible; Googlebot/2.1;, which is prone to get banned by ip-api.com.
I recommend you switch to an identifiable and unique user agent to avoid this.

**Comment by ourren** [comment]
add random agent now & thanks.

**Comment by vladc** [comment]
Random agent will get banned even faster. Use an identifiable and unique user agent to avoid this.

**Comment by ourren** [comment]
I think it is banned by ip per day.

**Comment by vladc** [comment]
Yes, but I audit logs for other things. This is something that I'll catch easily, and will result in a ban of the offending IP.

**Comment by ourren** [comment]
ok, thanks for you nice tips.

**Comment by ourren** [comment]
I have changed to unique agent, and comment the random agent.
